"""Attack scenario generators + the ground-truth ledger.

Ground truth is generated by the orchestrator at action time, not annotated after the
fact — post-hoc annotation is where label noise enters (Arp et al., 2022; see docs/04).

Two scenarios are implemented per BUILD-ORDER.md's condensed scope:

- ``mirai``: scan -> credential brute force -> C2 registration -> DDoS participation.
  Easy case: fan-out to many destinations, sustained egress spike.
- ``low_and_slow``: encrypted beaconing at long, jittered intervals with small payloads,
  designed to be nearly indistinguishable per-flow from legitimate telemetry. This is
  the deliberate hard case (docs/00) — if a stock anomaly detector catches it trivially,
  the simulated traffic is too easy and must be redesigned before anything downstream is
  trusted (MASTER-PLAN.md kill criteria).

Containment is enforced in code: every scenario only ever targets synthetic device ids
that exist in the current simulated fleet (see ``engine.py``); there is no code path by
which this module could address a real host.
"""

from __future__ import annotations

import random
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta

from argus.schemas import GroundTruthEvent


@dataclass
class AttackFlow:
    device_id: str
    ts: datetime
    proto: str
    dst: str
    port: int
    bytes_out: int
    bytes_in: int
    label: str


def run_mirai(device_id: str, t_start: datetime, rng: random.Random) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    flows: list[AttackFlow] = []
    events: list[GroundTruthEvent] = []
    t = t_start

    def emit(phase: str, duration_s: int, technique: str) -> tuple[datetime, datetime]:
        nonlocal t
        start = t
        end = start + timedelta(seconds=duration_s)
        events.append(GroundTruthEvent(
            event_id=str(uuid.uuid4()), scenario="mirai", phase=phase,
            t_start=start, t_end=end, src=device_id, dst=["10.10.0.0/24"],
            technique=technique,
        ))
        t = end
        return start, end

    scan_start, scan_end = emit("scan", 60, "T1595")
    tt = scan_start
    while tt < scan_end:
        flows.append(AttackFlow(device_id, tt, "tcp", f"10.10.0.{rng.randint(2, 240)}",
                                 rng.choice([22, 23, 80, 8080]), 60, 40, "attack:mirai:scan"))
        tt += timedelta(seconds=rng.uniform(0.5, 2))

    brute_start, brute_end = emit("bruteforce", 90, "T1110.001")
    tt = brute_start
    victim = f"10.10.0.{rng.randint(2, 240)}"
    while tt < brute_end:
        flows.append(AttackFlow(device_id, tt, "tcp", victim, 23, 90, 60, "attack:mirai:bruteforce"))
        tt += timedelta(seconds=rng.uniform(1, 3))

    c2_start, c2_end = emit("c2_registration", 20, "T1071")
    flows.append(AttackFlow(device_id, c2_start, "tcp", "203.0.113.77", 6667, 300, 150, "attack:mirai:c2_registration"))

    ddos_start, ddos_end = emit("ddos", 45, "T1498")
    tt = ddos_start
    while tt < ddos_end:
        flows.append(AttackFlow(device_id, tt, "udp", "198.51.100.5", 53, 1400, 60, "attack:mirai:ddos"))
        tt += timedelta(seconds=rng.uniform(0.05, 0.2))

    return flows, events


def run_low_and_slow(device_id: str, t_start: datetime, rng: random.Random,
                      duration_minutes: int = 180) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    """Beaconing C2 disguised as telemetry-cadence TLS.

    Deliberately shaped like the smart-speaker's benign beacon (docs/00: "the beaconing
    baseline scenario 7 must hide inside") -- similar byte sizes, similar TLS port,
    with only a long-horizon periodicity signature distinguishing it. A feature that
    only looks at single flows will not catch this by design.
    """
    events = [GroundTruthEvent(
        event_id=str(uuid.uuid4()), scenario="low_and_slow", phase="beacon",
        t_start=t_start, t_end=t_start + timedelta(minutes=duration_minutes),
        src=device_id, dst=["198.51.100.201"], technique="T1071.001",
    )]
    flows: list[AttackFlow] = []
    t = t_start
    end = t_start + timedelta(minutes=duration_minutes)
    interval = 480  # 8 minutes: longer + more regular than any benign device's period
    while t < end:
        jitter = rng.uniform(-20, 20)
        flows.append(AttackFlow(device_id, t, "tcp", "198.51.100.201", 443,
                                 rng.randint(300, 600), rng.randint(300, 600),
                                 "attack:low_and_slow:beacon"))
        t += timedelta(seconds=interval + jitter)
    return flows, events


SCENARIOS = {"mirai": run_mirai, "low_and_slow": run_low_and_slow}
