"""Attack scenario generators + the ground-truth ledger.

Ground truth is generated by the orchestrator at action time, not annotated after the
fact — post-hoc annotation is where label noise enters (Arp et al., 2022; see docs/04).

Two scenarios are implemented per BUILD-ORDER.md's condensed scope:

- ``mirai``: scan -> credential brute force -> C2 registration -> DDoS participation.
  Easy case: fan-out to many destinations, sustained egress spike.
- ``low_and_slow``: encrypted beaconing at long, jittered intervals with small payloads,
  designed to be nearly indistinguishable per-flow from legitimate telemetry. This is
  the deliberate hard case (docs/00) — if a stock anomaly detector catches it trivially,
  the simulated traffic is too easy and must be redesigned before anything downstream is
  trusted (MASTER-PLAN.md kill criteria).

Containment is enforced in code: every scenario only ever targets synthetic device ids
that exist in the current simulated fleet (see ``engine.py``); there is no code path by
which this module could address a real host.
"""

from __future__ import annotations

import random
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta

from argus.schemas import GroundTruthEvent


@dataclass
class AttackFlow:
    device_id: str
    ts: datetime
    proto: str
    dst: str
    port: int
    bytes_out: int
    bytes_in: int
    label: str
    tls_ja4: str | None = None
    dns_qname: str | None = None


def run_mirai(device_id: str, t_start: datetime, rng: random.Random) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    flows: list[AttackFlow] = []
    events: list[GroundTruthEvent] = []
    t = t_start

    def emit(phase: str, duration_s: int, technique: str) -> tuple[datetime, datetime]:
        nonlocal t
        start = t
        end = start + timedelta(seconds=duration_s)
        events.append(GroundTruthEvent(
            event_id=str(uuid.uuid4()), scenario="mirai", phase=phase,
            t_start=start, t_end=end, src=device_id, dst=["10.10.0.0/24"],
            technique=technique,
        ))
        t = end
        return start, end

    scan_start, scan_end = emit("scan", 60, "T1595")
    tt = scan_start
    while tt < scan_end:
        flows.append(AttackFlow(device_id, tt, "tcp", f"10.10.0.{rng.randint(2, 240)}",
                                 rng.choice([22, 23, 80, 8080]), 60, 40, "attack:mirai:scan"))
        tt += timedelta(seconds=rng.uniform(0.5, 2))

    brute_start, brute_end = emit("bruteforce", 90, "T1110.001")
    tt = brute_start
    victim = f"10.10.0.{rng.randint(2, 240)}"
    while tt < brute_end:
        flows.append(AttackFlow(device_id, tt, "tcp", victim, 23, 90, 60, "attack:mirai:bruteforce"))
        tt += timedelta(seconds=rng.uniform(1, 3))

    c2_start, c2_end = emit("c2_registration", 20, "T1071")
    flows.append(AttackFlow(device_id, c2_start, "tcp", "203.0.113.77", 6667, 300, 150, "attack:mirai:c2_registration"))

    ddos_start, ddos_end = emit("ddos", 45, "T1498")
    tt = ddos_start
    while tt < ddos_end:
        flows.append(AttackFlow(device_id, tt, "udp", "198.51.100.5", 53, 1400, 60, "attack:mirai:ddos"))
        tt += timedelta(seconds=rng.uniform(0.05, 0.2))

    return flows, events


def run_low_and_slow(device_id: str, t_start: datetime, rng: random.Random,
                      duration_minutes: int = 180) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    """Beaconing C2 disguised as telemetry-cadence TLS.

    Deliberately shaped like the smart-speaker's benign beacon (docs/00: "the beaconing
    baseline scenario 7 must hide inside") -- similar byte sizes, similar TLS port,
    with only a long-horizon periodicity signature distinguishing it. A feature that
    only looks at single flows will not catch this by design.
    """
    events = [GroundTruthEvent(
        event_id=str(uuid.uuid4()), scenario="low_and_slow", phase="beacon",
        t_start=t_start, t_end=t_start + timedelta(minutes=duration_minutes),
        src=device_id, dst=["198.51.100.201"], technique="T1071.001",
    )]
    flows: list[AttackFlow] = []
    t = t_start
    end = t_start + timedelta(minutes=duration_minutes)
    interval = 480  # 8 minutes: longer + more regular than any benign device's period
    while t < end:
        jitter = rng.uniform(-20, 20)
        flows.append(AttackFlow(device_id, t, "tcp", "198.51.100.201", 443,
                                 rng.randint(300, 600), rng.randint(300, 600),
                                 "attack:low_and_slow:beacon"))
        t += timedelta(seconds=interval + jitter)
    return flows, events


def run_mqtt_abuse(device_id: str, t_start: datetime, rng: random.Random) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    """Topic enumeration, then an unauthorised publish to a control topic (docs/02
    scenario 2: "broker interaction outside the device's declared policy" -- the
    highest-precision detection in the system, since it needs no model at all)."""
    flows: list[AttackFlow] = []
    t = t_start

    enum_start = t
    for _ in range(25):
        flows.append(AttackFlow(device_id, t, "tcp", "10.10.0.15", 8883, 70, 50, "attack:mqtt_abuse:enumeration"))
        t += timedelta(seconds=rng.uniform(0.3, 1.2))
    enum_end = t

    publish_start = t
    flows.append(AttackFlow(device_id, t, "tcp", "10.10.0.15", 8883, 220, 60, "attack:mqtt_abuse:unauthorised_publish"))
    t += timedelta(seconds=1)
    publish_end = t

    events = [
        GroundTruthEvent(str(uuid.uuid4()), "mqtt_abuse", "enumeration", enum_start, enum_end,
                          device_id, ["10.10.0.15"], "T1046"),
        GroundTruthEvent(str(uuid.uuid4()), "mqtt_abuse", "unauthorised_publish", publish_start, publish_end,
                          device_id, ["10.10.0.15"], "T1565"),
    ]
    return flows, events


def run_arp_spoof(device_id: str, t_start: datetime, rng: random.Random) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    """ARP spoofing / lateral movement (docs/02 scenario 3): a burst of unusual
    intra-LAN traffic to a device it has never talked to before, immediately after
    the (simulated) ARP poisoning window. ARGUS's live-testbed path doesn't yet
    extract L2/ARP fields (see STATUS.md's "not implemented" list), so this is
    represented at the level the current feature set can actually see: a
    new-destination, elevated-intra-LAN-volume signature."""
    flows: list[AttackFlow] = []
    t = t_start
    pivot_target = f"10.10.0.{rng.randint(20, 90)}"

    poison_start = t
    for _ in range(10):
        flows.append(AttackFlow(device_id, t, "udp", pivot_target, 0, 42, 0, "attack:arp_spoof:poison"))
        t += timedelta(seconds=rng.uniform(0.2, 0.6))
    poison_end = t

    lateral_start = t
    for _ in range(30):
        flows.append(AttackFlow(device_id, t, "tcp", pivot_target, rng.choice([445, 3389, 22]),
                                 rng.randint(200, 2000), rng.randint(100, 1500), "attack:arp_spoof:lateral_movement"))
        t += timedelta(seconds=rng.uniform(0.1, 0.5))
    lateral_end = t

    events = [
        GroundTruthEvent(str(uuid.uuid4()), "arp_spoof", "poison", poison_start, poison_end,
                          device_id, [pivot_target], "T1557.002"),
        GroundTruthEvent(str(uuid.uuid4()), "arp_spoof", "lateral_movement", lateral_start, lateral_end,
                          device_id, [pivot_target], "T1021"),
    ]
    return flows, events


def run_dns_tunnel(device_id: str, t_start: datetime, rng: random.Random) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    """DNS-tunnelled C2 (docs/02 scenario 4): high query-name entropy and volume to
    the resolver, exposing exactly the DNS feature group in docs/02."""
    flows: list[AttackFlow] = []
    t_end_last = t_start
    alphabet = "abcdefghijklmnopqrstuvwxyz0123456789"
    for _ in range(60):
        label = "".join(rng.choice(alphabet) for _ in range(rng.randint(30, 50)))
        qname = f"{label}.tunnel.example."
        flows.append(AttackFlow(device_id, t_end_last, "udp", "10.10.0.1", 53, 90, 512,
                                 "attack:dns_tunnel:exfil", dns_qname=qname))
        t_end_last += timedelta(seconds=rng.uniform(0.5, 2.0))

    events = [GroundTruthEvent(
        str(uuid.uuid4()), "dns_tunnel", "exfil", t_start, t_end_last,
        device_id, ["10.10.0.1"], "T1071.004",
    )]
    return flows, events


def run_identity_spoof(device_id: str, t_start: datetime, rng: random.Random) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    """Device identity spoofing (docs/02 scenario 5, "Hard"): an attacker mimics a
    legitimate device's traffic profile but its TLS client fingerprint (JA4) is
    different from what the baseline recorded for this device_id -- a subtle
    mismatch, not an obvious volume anomaly, matching the scenario's difficulty."""
    flows: list[AttackFlow] = []
    t = t_start
    spoofed_ja4 = f"ja4-spoofed-{rng.randint(1000, 9999)}"
    for _ in range(15):
        flows.append(AttackFlow(device_id, t, "tcp", "203.0.113.44", 443, rng.randint(200, 800),
                                 rng.randint(200, 800), "attack:identity_spoof:fingerprint_mismatch",
                                 tls_ja4=spoofed_ja4))
        t += timedelta(seconds=rng.uniform(20, 60))

    events = [GroundTruthEvent(
        str(uuid.uuid4()), "identity_spoof", "fingerprint_mismatch", t_start, t,
        device_id, ["203.0.113.44"], "T1036",
    )]
    return flows, events


def run_ota_spoof(device_id: str, t_start: datetime, rng: random.Random) -> tuple[list[AttackFlow], list[GroundTruthEvent]]:
    """OTA update spoofing (docs/02 scenario 6): a firmware fetch from an endpoint
    outside the device's declared OTA policy -- same detection mechanism as MQTT
    abuse (a policy violation), different phase of the attack chain."""
    t_start_fetch = t_start
    flow = AttackFlow(device_id, t_start, "tcp", "198.51.100.230", 443, 40000, 900,
                       "attack:ota_spoof:malicious_fetch")
    t_end_fetch = t_start + timedelta(seconds=8)

    events = [GroundTruthEvent(
        str(uuid.uuid4()), "ota_spoof", "malicious_fetch", t_start_fetch, t_end_fetch,
        device_id, ["198.51.100.230"], "T1195.002",
    )]
    return [flow], events


SCENARIOS = {
    "mirai": run_mirai,
    "low_and_slow": run_low_and_slow,
    "mqtt_abuse": run_mqtt_abuse,
    "arp_spoof": run_arp_spoof,
    "dns_tunnel": run_dns_tunnel,
    "identity_spoof": run_identity_spoof,
    "ota_spoof": run_ota_spoof,
}
